  [mcp_servers.idea]
    url = "http://127.0.0.1:64342/stream"

[mcp_servers.idea.tools.apply_patch]
approval_mode = "approve"

[mcp_servers.idea.tools.build_project]
approval_mode = "approve"

[mcp_servers.idea.tools.create_new_file]
approval_mode = "approve"

[mcp_servers.idea.tools.mixin_move_file]
approval_mode = "approve"

[mcp_servers.idea.tools.execute_run_configuration]
approval_mode = "approve"
