package org.unitego.lobecorp.conductor.config;

/// 指挥家运行规则与业务参数的集中定义。
public interface ConductorRules {
	int DIRECTORY_SYNC_INTERVAL_TICKS = 20;
	/// 指挥家镜头观察位置的客户端同步间隔，单位为 tick。
	int VIEW_SYNC_INTERVAL_TICKS = 5;
	/// 镜头停止同步后释放观察区块票据的等待时间，单位为 tick。
	int VIEW_TIMEOUT_TICKS = 40;
	double TARGET_SEARCH_RANGE = 32.0D;
	double TEAM_AGGRO_SHARE_RANGE = 16.0D;
	double PATROL_RADIUS = 20.0D;
	double GUARD_RADIUS = 10.0D;
	double ARRIVAL_DISTANCE = 0.35D;
	double DRAGON_ARRIVAL_DISTANCE = 4.0D;
	double FINAL_APPROACH_DISTANCE = 1.5D;
	double FORMATION_GAP = 0.75D;
	double FORMATION_DIRECTION_EPSILON = 1.0E-8D;
	double FORMATION_DEFAULT_WIDTH = 1.0D;
	double ENTITY_AVOIDANCE_MARGIN = 0.25D;
	double ENTITY_AVOIDANCE_STRENGTH = 0.08D;
	double MOVEMENT_SPEED = 1.0D;
	double NATURAL_MOVEMENT_SPEED = -1.0D;
	double ENTITY_AVOIDANCE_LOOKAHEAD = 2.0D;
	int ENTITY_AVOIDANCE_SIDES = 2;
	int MOVEMENT_RETRY_TICKS = 10;
	int PATH_SEGMENT_RANGE = 64;
	double PATH_MIN_PROGRESS = 0.5D;
	int MOVEMENT_STALL_TICKS = 40;
	int MOVEMENT_MAX_REPLANS = 3;
	double MOVEMENT_PROGRESS_DISTANCE = 0.1D;
	double ARRIVAL_HEIGHT = 0.5D;
	int SLOT_SEARCH_RADIUS = 4;
	double PATH_SAMPLE_DISTANCE = 0.25D;
	double SUPPORT_PROBE_DEPTH = 0.1D;
	int POINT_ATTACK_INTERVAL_TICKS = 40;
	int BOW_DRAW_TICKS = 20;
	int CROSSBOW_READY_DELAY_TICKS = 20;
	int CROSSBOW_READY_RANDOM_TICKS = 20;
	int BREEZE_CHARGE_TICKS = 15;
	int BREEZE_RECOVER_TICKS = 4;
	int BREEZE_SHOOT_COOLDOWN_TICKS = 10;
	float BREEZE_PROJECTILE_SPEED = 0.7F;
	float BREEZE_UNCERTAINTY_BASE = 5.0F;
	float BREEZE_UNCERTAINTY_PER_DIFFICULTY = 4.0F;
	float BREEZE_SHOOT_VOLUME = 1.5F;
	float POINT_ATTACK_POWER = 1.0F;
	float CROSSBOW_POINT_ATTACK_POWER = 1.6F;
	float POINT_ATTACK_UNCERTAINTY_BASE = 14.0F;
	float POINT_ATTACK_UNCERTAINTY_PER_DIFFICULTY = 4.0F;
	int MANUAL_ABILITY_REQUEST_TICKS = 10;
	double WARDEN_SONIC_BOOM_HORIZONTAL_RANGE = 15.0D;
	double WARDEN_SONIC_BOOM_VERTICAL_RANGE = 20.0D;
	double WARDEN_SONIC_BOOM_PREVIEW_HALF_WIDTH = 0.75D;
	double WARDEN_SONIC_BOOM_DAMAGE = 10.0D;
	int WARDEN_SONIC_WINDUP_TICKS = 34;
	int WARDEN_SONIC_DURATION_TICKS = 60;
	int WARDEN_SONIC_PARTICLE_EXTENSION = 7;
	byte WARDEN_SONIC_EVENT = 62;
	float WARDEN_SONIC_VOLUME = 3.0F;
	float WARDEN_SONIC_PITCH = 1.0F;
	double WARDEN_SONIC_KNOCKBACK_HORIZONTAL = 2.5D;
	double WARDEN_SONIC_KNOCKBACK_VERTICAL = 0.5D;
	int COLOR_HUE_STEPS = 360;
	float COLOR_SATURATION = 0.75F;
	float COLOR_BRIGHTNESS = 0.95F;
}
