package org.unitego.lobecorp.client.conductor.hud;

import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import org.unitego.lobecorp.conductor.ability.WardenSonicBoomAbility;
import org.unitego.lobecorp.registry.entity.skill.SweeperSkills;
import org.unitego.lobecorp.util.TranslationKeys;

public interface ConductorTexts {
	String ORDER_CLEANUP = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ORDER_CLEANUP;
	String ORDER_REASSEMBLE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ORDER_REASSEMBLE;
	String MOVE_ARRIVED = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_MOVE_ARRIVED;
	String MOVE_UNREACHABLE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_MOVE_UNREACHABLE;
	String MOVE_CANCELED = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_MOVE_CANCELED;
	String CLEANUP_DESCRIPTION = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_CLEANUP_DESCRIPTION;
	String REASSEMBLE_DESCRIPTION = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_REASSEMBLE_DESCRIPTION;
	String SONIC_DESCRIPTION = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_SONIC_DESCRIPTION;
	String CATEGORY = TranslationKeys.KEY_CATEGORY_LOBECORP_CONDUCTOR;
	String TOGGLE = TranslationKeys.KEY_LOBECORP_CONDUCTOR_TOGGLE;
	String MENU = TranslationKeys.KEY_LOBECORP_CONDUCTOR_MENU;
	String FOLLOW = TranslationKeys.KEY_LOBECORP_CONDUCTOR_FOLLOW;
	String ROTATE_LEFT = TranslationKeys.KEY_LOBECORP_CONDUCTOR_ROTATE_LEFT;
	String ROTATE_RIGHT = TranslationKeys.KEY_LOBECORP_CONDUCTOR_ROTATE_RIGHT;
	String TITLE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_TITLE;
	String SETTINGS = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_SETTINGS;
	String SEARCH = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_SEARCH;
	String CLEAR_SEARCH = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_CLEAR_SEARCH;
	String SEARCH_SKILLS = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_SEARCH_SKILLS;
	String ROSTER_COUNT = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ROSTER_COUNT;
	String NO_MATCHING_MEMBERS = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_NO_MATCHING_MEMBERS;
	String NO_MATCHING_SKILLS = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_NO_MATCHING_SKILLS;
	String NO_SELECTION = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_NO_SELECTION;
	String NO_SKILLS = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_NO_SKILLS;
	String UNKNOWN_HEALTH = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_UNKNOWN_HEALTH;
	String UNKNOWN_ATTRIBUTES = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_UNKNOWN_ATTRIBUTES;
	String ATTRIBUTES = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ATTRIBUTES;
	String DISTANCE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_DISTANCE;
	String DIMENSION = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_DIMENSION;
	String KNOWN_HEALTH = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_KNOWN_HEALTH;
	String AVERAGE_HEALTH = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_AVERAGE_HEALTH;
	String REMOTE_FOCUS = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_REMOTE_FOCUS;
	String READY = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_READY;
	String REDUCE_MOTION_ON = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_REDUCE_MOTION_ON;
	String REDUCE_MOTION_OFF = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_REDUCE_MOTION_OFF;
	String EFFECT = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_EFFECT;
	String EMPTY_TEAM = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_EMPTY_TEAM;
	String REMOTE_SKILLS = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_REMOTE_SKILLS;
	String HEALTH_PERCENT = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_HEALTH_PERCENT;
	String OFFLINE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_OFFLINE;
	String DAMAGE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_DAMAGE;
	String DAMAGE_DYNAMIC = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_DAMAGE_DYNAMIC;
	String DAMAGE_NONE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_DAMAGE_NONE;
	String TYPE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_TYPE;
	String TYPE_BASIC = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_TYPE_BASIC;
	String TYPE_ATTACK = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_TYPE_ATTACK;
	String TYPE_SUPPORT = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_TYPE_SUPPORT;
	String TARGET = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_TARGET;
	String TARGET_SELF = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_TARGET_SELF;
	String TARGET_ENTITY = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_TARGET_ENTITY;
	String TARGET_POSITION = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_TARGET_POSITION;
	String TARGET_EITHER = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_TARGET_EITHER;
	String RANGE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_RANGE;
	String RANGE_UNSPECIFIED = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_RANGE_UNSPECIFIED;
	String RANGE_SELF = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_RANGE_SELF;
	String COOLDOWN_TOTAL = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_COOLDOWN_TOTAL;
	String COOLDOWN_REMAINING = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_COOLDOWN_REMAINING;
	String TEAM = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_TEAM;
	String TEAM_MANAGEMENT = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_TEAM_MANAGEMENT;
	String CONTROLS = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_CONTROLS;
	String REMOTE_ORDERS = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_REMOTE_ORDERS;
	String CREATE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_CREATE;
	String ASSIGN = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ASSIGN;
	String RELEASE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_RELEASE;
	String FORMATION_SCATTERED = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_FORMATION_SCATTERED;
	String FORMATION_REGULAR = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_FORMATION_REGULAR;
	String FORMATION_UNIFORM = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_FORMATION_UNIFORM;
	String FORMATION_SCATTERED_DESCRIPTION = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_FORMATION_SCATTERED_DESCRIPTION;
	String FORMATION_REGULAR_DESCRIPTION = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_FORMATION_REGULAR_DESCRIPTION;
	String FORMATION_UNIFORM_DESCRIPTION = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_FORMATION_UNIFORM_DESCRIPTION;
	String MOVE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_MOVE;
	String ATTACK = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ATTACK;
	String STOP = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_STOP;
	String ATTACK_AI = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ATTACK_AI;
	String ATTACK_BASIC = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ATTACK_BASIC;
	String ATTACK_MODE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ATTACK_MODE;
	String BEHAVIOR_MODE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_BEHAVIOR_MODE;
	String BEHAVIOR_VALUE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_BEHAVIOR_VALUE;
	String BEHAVIOR_ACTIVE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_BEHAVIOR_ACTIVE;
	String BEHAVIOR_PASSIVE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_BEHAVIOR_PASSIVE;
	String BEHAVIOR_NEUTRAL = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_BEHAVIOR_NEUTRAL;
	String ACTIVITY_MODE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ACTIVITY_MODE;
	String ACTIVITY_VALUE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ACTIVITY_VALUE;
	String BEHAVIOR_PATROL = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_BEHAVIOR_PATROL;
	String BEHAVIOR_IDLE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_BEHAVIOR_IDLE;
	String BEHAVIOR_GUARD = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_BEHAVIOR_GUARD;
	String BEHAVIOR_STANDBY = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_BEHAVIOR_STANDBY;
	String SKILL_UNAVAILABLE_COOLDOWN = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_SKILL_UNAVAILABLE_COOLDOWN;
	String SKILL_UNAVAILABLE_CASTING = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_SKILL_UNAVAILABLE_CASTING;
	String SKILL_UNAVAILABLE_CONDITION = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_SKILL_UNAVAILABLE_CONDITION;
	String SKILL_UNAVAILABLE_TARGET = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_SKILL_UNAVAILABLE_TARGET;
	String SKILL_OUT_OF_RANGE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_SKILL_OUT_OF_RANGE;
	String SKILL_COOLDOWN = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_SKILL_COOLDOWN;
	String REMOTE_MOVE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_REMOTE_MOVE;
	String REMOTE_ATTACK = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_REMOTE_ATTACK;
	String REMOTE_CAST = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_REMOTE_CAST;
	String TARGET_UUID = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_TARGET_UUID;
	String SKILL_ID = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_SKILL_ID;
	String WAR = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_WAR;
	String PEACE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_PEACE;
	String LOAD_ON = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_LOAD_ON;
	String LOAD_OFF = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_LOAD_OFF;
	String FULL = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_FULL;
	String COMMAND = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_COMMAND;
	String SOFT = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_SOFT;
	String SELECTED = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_SELECTED;
	String SKILLS = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_SKILLS;
	String CLOSE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_CLOSE;
	String NEXT = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_NEXT;
	String PREVIOUS = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_PREVIOUS;
	String ENEMY_TEAM = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ENEMY_TEAM;
	String X = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_X;
	String Y = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_Y;
	String Z = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_Z;
	String COLOR = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_COLOR;
	String APPLY_COLOR = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_APPLY_COLOR;
	String HEALTH = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_HEALTH;
	String ORDER_NONE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ORDER_NONE;
	String ORDER_MOVE = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ORDER_MOVE;
	String ORDER_ATTACK = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ORDER_ATTACK;
	String ORDER_ATTACK_POINT = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ORDER_ATTACK_POINT;
	String ORDER_RETURN = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ORDER_RETURN;
	String ORDER_STOP = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_ORDER_STOP;
	String NO_TEAM = TranslationKeys.SCREEN_LOBECORP_CONDUCTOR_NO_TEAM;
	String SKILL_TRANSLATION_PREFIX = "entity_skill.";
	String ABILITY_TRANSLATION_PREFIX = "conductor_ability.";

	static String skillName(Identifier id) {
		return SKILL_TRANSLATION_PREFIX + id.getNamespace() + "." + id.getPath();
	}

	static String abilityName(Identifier id) {
		return ABILITY_TRANSLATION_PREFIX + id.getNamespace() + "." + id.getPath();
	}

	static Component abilityDescription(Identifier ability) {
		if (ability.equals(SweeperSkills.SWEEP.get().id()))
			return Component.translatable(CLEANUP_DESCRIPTION);
		if (ability.equals(SweeperSkills.REASSEMBLE.get().id()))
			return Component.translatable(REASSEMBLE_DESCRIPTION);
		if (ability.equals(WardenSonicBoomAbility.ID))
			return Component.translatable(SONIC_DESCRIPTION);
		return Component.empty();
	}
}
